### PR TITLE
Added proxy support

### PR DESCRIPTION
**Pull request by fqrious**
Added proxy support

```javascript
const initMyTls = require('mytls');

// Typescript: import initMyTls from 'mytls';

(async () => {
  const myTls = await initMyTls();

  const response = await myTls('https://ipv4.icanhazip.com', {
    body: '',
    headers: {
      'user-agent': 'customheaders',
    },
    ja3: '771,255-49195-49199-49196-49200-49171-49172-156-157-47-53,0-10-11-13,23-24,0',
   proxy: 'http://random:passwd@localhost:8180',
  });
 console.log('new_ip:', response.body)
})();

```

### CODE REVIEW

**Comment by zedd3v** [comment]
Using proxies this way doesn't use the tls settings.

**Comment by incizzle** [comment]
Is their anyways to get this to work while also keeping the tls settings? This would be a awesome feature to have.

**Comment by zedd3v** [comment]
Right now I only found a method which includes changing the go src directly.
Still looking for a plug in solution

**Comment by fqrious** [comment]
I finally found a way to get proxies to work but I couldn't get mytls to work on akamai.

You only need to change how you initialize your transport object, I will probably submits PR later today.

Therefore, I don't think you need to change anything in golang src to make it work

**Comment by incizzle** [comment]
Awesome looking forward to it 👌

**Comment by fqrious** [comment]
@incizzle fixed in #4

**Pull request closed without merging**
